site_name: Документация проекта 1430
theme:
  name: material
  highlightjs: true
plugins:
  - search
nav:
  - О проекте: 'index.md'
  - Бот с интерактивными заданиями:
    - Архитектура: 'new_bot/arch.md'
    - Код: 'new_bot/code.md'
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences