site_name: Документация проекта 1430
theme:
  name: material
  highlightjs: true
plugins:
  - search
nav:
  - О проекте: 'index.md'
  - Бот с интерактивными заданиями:
    - Технические требования: 'new_bot/requirements.md'
    - Архитектура:
      - Файловая структура: 'new_bot/struc.md'
      - Архиетктура проекта: 'new_bot/arch.md'
      - Машина состояний: 'new_bot/fsm.md'
    - Модуль WebApp: 'new_bot/webapp.md'
    - Тестирование : 'new_bot/tests.md'
    - Запуск модулей: 'new_bot/run.md'
  - Бот вводного курса по истории криптографии:
    - Справка: 'old_bot/disclaim.md'
    - Технические требования: 'old_bot/requirements.md'
    - Архитектура:
      - Файловая структура: 'old_bot/struc.md'
      - Общее описание: 'old_bot/integr.md'
      - Архиетктура БД: 'old_bot/arch_bd.md'
      - Архиетктура API: 'old_bot/arch_api.md'
    - Модуль опросов по главам: 'old_bot/tests.md'
    - Запуск модулей: 'old_bot/run.md'

extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format